name: Publish new release

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v1

      - name: "Save tag in state"
        run: |
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: "Update control file with tag version"
        run: |
          sed 's/Version.*/Version: ${{ env.tag }}/' package/DEBIAN/control

      - name: "Build packages"
        run: |
          sudo apt install -y alien
          
          make build
          make pack

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            dist/*
            !dist/.gitkeep

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions: write-all
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/

      - name: "Create release"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          files: |
            dist/*
